apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
 -  path: ./cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-image-updater-config   
resources:
  - github.com/argoproj-labs/argocd-image-updater/manifests/base