apiVersion: v2
name: vault-operator
version: 1.6.0
appVersion: 1.11.0
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/banzaicloud/bank-vaults
  - https://github.com/banzaicloud/banzai-charts
dependencies:
  - name: common-app
    repository: https://nolte.github.io/argo-charts/
    version: 1.2.0