apiVersion: v2
name: harbor
version: 1.6.0
appVersion: v1.5.3
sources:
- https://github.com/goharbor/harbor
- https://github.com/goharbor/harbor-helm
dependencies:
  - name: common-app
    repository: https://nolte.github.io/argo-charts/
    version: 1.2.0