
# https://www.vaultproject.io/docs/commands/operator/unseal
# https://www.vaultproject.io/docs/platform/k8s/helm/run
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: flow-unseal
spec:
  entrypoint: unseal-flow
  arguments:
    parameters:
      - name: labelSelector
        value: "component=server"
      - name: namespace
        value: "vault"
      - name: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY           
  templates:
    - name: unseal-flow
      inputs:
        parameters:
          - name: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY                 
      steps:
        - - name: select-pods
            arguments:
              parameters:
                - name: labelSelector
                  value: "component=server"
                - name: namespace
                  value: "vault"
            templateRef:
              name: k8s-list
              template: get
        - - name: extract-names
            templateRef:
              name: jq-exec
              template: exec 
            arguments:
              parameters:
              - name: jsonExpression
                value: "{{steps.select-pods.outputs.parameters.pods}}|.items[].metadata.name|[.]"
            
        - - name: unseal
            template: unseal-pod
            arguments:
              parameters:
              - name: podName
                value: "{{item}}"
              - name: namespace
                value: "vault"
              - name: AWS_ACCESS_KEY_ID
                value: "{{inputs.parameters.AWS_ACCESS_KEY_ID}}"
              - name: AWS_SECRET_ACCESS_KEY   
                value: "{{inputs.parameters.AWS_SECRET_ACCESS_KEY}}"
            withParam: "{{steps.extract-names.outputs.parameters.result}}"


    - name: unseal-pod
      inputs:
        parameters:
          - name: podName
          - name: namespace
          - name: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY          
      steps:  
       - - name: unseal-pod-keys
           templateRef:
             name: k8s-exec
             template: exec
           continueOn:
              failed: true
           arguments:
             parameters:
             - name: podName
               value: "{{inputs.parameters.podName}}"
             - name: namespace
               value: "{{inputs.parameters.namespace}}"
             - name: execCommand
               value: "vault status -format=json"

       - - name: vault-status-parse
           templateRef:
             name: jq-exec
             template: exec
           arguments:
             parameters:
             - name: jsonExpression
               value: "{{steps.unseal-pod-keys.outputs.parameters.result}}|.sealed"


       - - name: operator-init
           when: "{{steps.unseal-pod-keys.exitCode}} == 2"
           template: unseal-token
           arguments:
             parameters:
             - name: podName
               value: "{{inputs.parameters.podName}}"
             - name: namespace
               value: "{{inputs.parameters.namespace}}"
             - name: AWS_SECRET_ACCESS_KEY
               value: "{{inputs.parameters.AWS_SECRET_ACCESS_KEY}}"
             - name: AWS_ACCESS_KEY_ID
               value: "{{inputs.parameters.AWS_ACCESS_KEY_ID}}"


    - name: unseal-token
      inputs:
        parameters:
          - name: podName
          - name: namespace
          - name: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
      steps:
       - - name: operator-init
           templateRef:
             name: k8s-exec
             template: exec        
           arguments:
             parameters:
             - name: podName
               value: "{{inputs.parameters.podName}}"
             - name: namespace
               value: "{{inputs.parameters.namespace}}"
             - name: execCommand
               value: "vault operator init -format=json"

       - - name: vault-save-keys
           templateRef:
             name: k8s-secret
             template: write
           arguments:
             parameters:
             - name: content
               value: "{{steps.operator-init.outputs.parameters.result}}"
             - name: namespace
               value: vault
             - name: secretName
               value: vault-init-tokens

       - - name: vault-extract-unseal-keys
           templateRef:
             name: jq-exec
             template: exec
           arguments:
             parameters:
             - name: jsonExpression
               value: "{{steps.operator-init.outputs.parameters.result}}|.unseal_keys_b64[0:3]"

       - - name: unseal-token
           templateRef:
             name: k8s-exec
             template: exec
           withParam: "{{steps.vault-extract-unseal-keys.outputs.parameters.result}}"  
           arguments:
             parameters:
             - name: podName
               value: "{{inputs.parameters.podName}}"
             - name: namespace
               value: "{{inputs.parameters.namespace}}"
             - name: execCommand
               value: "vault operator unseal {{item}}"

       - - name: wait-for-vault
           template: wait-vault


       - - name: vault-extract-root-token
           templateRef:
             name: jq-exec
             template: exec
           arguments:
             parameters:
             - name: jsonExpression
               value: "{{steps.operator-init.outputs.parameters.result}}|.root_token"

       - - name: vault-bootstrap
           templateRef:
             name: vault-bootstrap
             template: bootstrap
           arguments:
             parameters:
             - name: AWS_ACCESS_KEY_ID
               value: "{{inputs.parameters.AWS_ACCESS_KEY_ID}}"
             - name: AWS_SECRET_ACCESS_KEY
               value: "{{inputs.parameters.AWS_SECRET_ACCESS_KEY}}"
             - name: VAULT_TOKEN
               value: "{{steps.vault-extract-root-token.outputs.parameters.result}}" 
    - name: wait-vault
      resource:
        action: get
        successCondition: status.readyReplicas > 0
        failureCondition: status.currentReplicas = 0
        manifest: |
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            namespace: vault
            name: vault