apiVersion: v2
name: konfigurator
version: 1.5.0
sources:
  - https://github.com/stakater/Konfigurator
dependencies:
  - name: common-app
    repository: https://nolte.github.io/argo-charts/
    version: 1.1.1