apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: argo
spec:
  entrypoint: login
  arguments:
    parameters:
      - name: username
        value: admin
  templates:
    - name: login
      steps:
        - - name: call-initial-user  
            arguments:
              parameters:
              - name: username
                value: "{{workflow.parameters.username}}"
            templateRef:
              name: argocd-initial
              template: initial-user     
