workflow:
  namespace: argo-workflow

vault:
  server:
    ingress:
      enabled: true
      annotations:
        ingress.kubernetes.io/force-ssl-redirect: "true"
      tls:
        - hosts:
            - vault.172-17-0-1.sslip.io
          secretName: vault-cert-tls
      hosts:
        - host: vault.172-17-0-1.sslip.io
          paths: []

  injector:
    certs:
      # secretName is the name of the secret that has the TLS certificate and
      # private key to serve the injector webhook. If this is null, then the
      # injector will default to its automatic management mode that will assign
      # a service account to the injector to generate its own certificates.
      secretName: vault-cert-tls
      dnsNames: []
      issuerRef: 
        name: cluster-issuer
        kind: ClusterIssuer
        # - vault.test.de
