destination:
  namespace: argo-workflow

source:
  repoURL: https://argoproj.github.io/argo-helm
  chart: argo
  helm:
    releaseName: argo
    parameters:
      - name: workflow.namespace
        value: "argo-workflow"
      - name: workflow.rbac.create
        value: "true"
      - name: workflow.serviceAccount.create
        value: "true"
      - name: controller.containerRuntimeExecutor
        value: "k8sapi"