apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: seed
  source:
    helm:
      values: |
        apps:
          cluster-issuer:
            destination:
              namespace: cert-manager
            source: |
              repoURL: https://github.com/nolte/argo-charts.git
              targetRevision: feature/collection-chart
              path: charts/cert-manager-issuer
    path: charts/common-apps-argocd
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: feature/collection-chart
  syncPolicy: {}