apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflow
namePrefix: tf-

generatorOptions:
  disableNameSuffixHash: true

#secretGenerator:
#- name: state-auth  
#  literals:
#    - AWS_S3_ENDPOINT="http://minio.minio.svc:9000"
#    - AWS_ACCESS_KEY_ID="accessKey"
#    - AWS_SECRET_ACCESS_KEY="secretKey"

#    - MINIO_ENDPOINT="minio.minio.svc:9000"
#    - MINIO_ACCESS_KEY="accessKey"
#    - MINIO_SECRET_KEY="secretKey"
#    - MINIO_ENABLE_HTTPS=false

resources:
  - flow-terraground.yaml