apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: secret
spec:
  entrypoint: write
  arguments:
    parameters:
    - name: podName
    - name: namespace
    - name: content
  templates:  
  - name: write
    inputs:
      parameters:
      - name: secretName
      - name: namespace
      - name: content
    container:
      image: bitnami/kubectl
      command: [sh, -c]
      args: ["echo \"{{inputs.parameters.content}}\" > /tmp/content.json && kubectl -n {{inputs.parameters.namespace}} create secret generic {{inputs.parameters.secretName}} --from-file=/tmp/content.json"]