apiVersion: {{ include "common.capabilities.application.apiVersion" . }}
kind: Application
metadata:
  name: {{ include "common.names.fullname" . }}
  finalizers:
  {{- include "common.finalizers" . | nindent 4 }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.controllerLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.controllerAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  project: default
  source:
    repoURL: https://nolte.github.io/argo-charts/
    targetRevision: 1.0.0
    chart: collection-argocd-baseline
  destination:
  {{- with .Values.destination }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  helm:
    releaseName:  {{ .Values.releaseName }}
    values: |
      argocd-project-contour:
        enabled: false
      argocd-cert-manager:
        enabled: false
      argocd-monitoring:
        enabled: false
      argocd-reloader:
        enabled: false
      argocd-forecastle:
        enabled: false  
      argocd-konfigurator:
        enabled: false 
  project: {{ .Values.project }}
  source:
  {{- include "common.classes.source" . | nindent 4 }}
  syncPolicy:
  {{- with .Values.syncPolicy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ignoreDifferences }}
  ignoreDifferences:
  {{- toYaml . | nindent 4 }}
  {{- end }}