# https://github.com/stakater/Forecastle/blob/master/deployments/kubernetes/chart/forecastle/values.yaml
destination:
  namespace: argocd
source:
  path: deployments/kubernetes/chart/forecastle
  repoURL: https://github.com/stakater/Forecastle.git
  targetRevision: v1.0.62
