apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows
spec:
  destination:
    name: in-cluster
    namespace: argo-workflow
  project: cicd
  source:
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: HEAD
    path: apps/workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true    