apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seed-argo
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: seed
  source:
    repoURL: https://nolte.github.io/argo-charts/
    targetRevision: 1.6.1
    chart: argocd-argo-workflow
    helm:
      releaseName: argo-workflow
      version: v3.5.1
      values: |
        fullnameOverride: argo-workflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true