apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: cicd
  source:
    repoURL: https://nolte.github.io/argo-charts/
    targetRevision: 1.6.1
    chart: argocd-argo-workflow
    helm:
      fullnameOverride: argo-workflow
      releaseName: argo-workflow
      version: v3.5.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true