apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
spec:
  destination:
    name: in-cluster
    namespace: argo-workflow
  project: cicd
  source:
    repoURL: https://nolte.github.io/argo-charts/
    targetRevision: HEAD
    path: apps/workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true    