apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baseline
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: seed
  source:
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: feature/collection-chart
    path: charts/common-apps-argocd
    helm:
      releaseName: baseline
      version: v3.5.1
      valueFiles: ['values-env-kind.yaml','values-apps-baseline.yaml']

  syncPolicy: {}