apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baseline
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: seed
  source:
    helm:
      releaseName: baseline
      values: |
        global:
          project: baseline
        apps:
          velero:
            enabled: false
            destination:
              namespace: velero          
            source: |
              chart: velero
              repoURL: https://vmware-tanzu.github.io/helm-charts
              targetRevision: 1.5.3
          project-contour:
            enabled: true
            destination:
              namespace: project-contour
            source: |
              repoURL: https://charts.bitnami.com/bitnami
              chart: contour
              targetRevision: 4.1.0
              helm:
                releaseName: project-contour
                version: v3.5.1
                values: |
                  prometheus:
                    serviceMonitor:
                      enabled: true
                  envoy:
                    service:
                      type: NodePort
                  contour:
                    manageCRDs: true
          argocd-image-updater:
            enabled: true
            destination: 
              namespace: argocd  
            source: |
              path: apps/argocd-image-updater/
              repoURL: https://github.com/nolte/argo-charts.git
              targetRevision: HEAD
          reloader:
            enabled: true
            destination: 
              namespace: operators  
            source: |
              path: deployments/kubernetes/chart/reloader
              repoURL: https://github.com/stakater/Reloader.git
              helm:
                version: v3.5.1

          konfigurator:
            enabled: true
            destination: 
              namespace: operators   
            source: |
              repoURL: https://github.com/stakater/Konfigurator.git
              path: deployments/kubernetes/chart/konfigurator
              targetRevision: v0.0.26
              helm:
                version: v3.5.1
                values: |
                  konfigurator:
                    deployCRD: true

          cert-manager:
            enabled: true
            destination: 
              namespace: cert-manager
            source: |
              repoURL: https://charts.jetstack.io
              chart: cert-manager
              targetRevision: v1.1.0
              helm:
                releaseName: cert-manager
                version: v3.5.1
                values: |
                  installCRDs: true
                  prometheus:
                    enabled: true
                    servicemonitor:
                      enabled: true

          monitoring:
            enabled: true
            destination: 
              namespace: monitoring   
            source: |
              repoURL: https://prometheus-community.github.io/helm-charts
              chart: kube-prometheus-stack
              targetRevision: 13.4.1
              helm:
                version: v3.5.1
                releaseName: monitoring
                values: |
                  grafana:
                    enabled: false
          forecastle:
            enabled: true
            destination: 
              namespace: operators   
            source: |
              path: deployments/kubernetes/chart/forecastle
              repoURL: https://github.com/stakater/Forecastle.git
              targetRevision: v1.0.62
              helm:
                version: v3.5.1
                values: |
                   forecastle:
                     ingress:
                       enabled: {{ .Values.global.ingress.enabled }}
                       annotations:
                         ingress.kubernetes.io/force-ssl-redirect: "true"
                         cert-manager.io/cluster-issuer: {{ .Values.global.ingress.clusterIssuer }}
                       tls:
                         - hosts:
                             - forecastle.{{ .Values.global.ingress.domain }}
                           secretName: forecastle-cert
                       hosts:
                         - host: forecastle.{{ .Values.global.ingress.domain }}
                           paths:
                           - /        
      version: v3.5.1
    path: charts/common-apps-argocd
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: feature/collection-chart
  syncPolicy: {}