apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baseline
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: seed
  source:
    helm:
      parameters: []
      releaseName: baseline
      values: |
        global:
          project: baseline
        grafana:
          enabled: false
        metallb:
          powerdns:
            address: "192.168.144.0/20"
          addressPools:
            -  name: "powerdns"
               protocol: "layer2"
               addresses: 
                 - "192.168.144.0/20"
        apps:
          metallb:
            enabled: true
            destination:
              namespace: metallb
            source: |
              chart: metallb
              repoURL: https://charts.bitnami.com/bitnami
              targetRevision: 2.3.2
              helm:
                version: v3
                # https://github.com/bitnami/charts/blob/master/bitnami/metallb/values.yaml
                values: |
                  configInline:
                    {{ toYaml .Values.metallb.addressPools | nintend 8 }}     
          external-dns:
            enabled: true
            destination:
              namespace: kube-system
            source: |
              chart: external-dns
              targetRevision: 4.8.6
              repoURL: https://charts.bitnami.com/bitnami
              helm:
                values: |
                  provider: pdns
                  txtOwnerId: kind-roger
                  domainFilters:
                    - smart-home.k8sservices.local
                  pdns:
                    apiUrl: "http://powerdns-webserver.powerdns.svc"
                    apiPort: "8081"
                    apiKey: "supersecretpw"        
          postgres-operator:
            enabled: true
            destination:
              namespace: operators
            source: |
              repoURL: https://github.com/zalando/postgres-operator.git
              path: charts/postgres-operator
              targetRevision: v1.6.1
              helm:
                version: v3
                # https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/values.yaml

          argocd:
            enabled: true
            destination:
              namespace: argocd
            source: |
              repoURL: https://nolte.github.io/argo-charts/
              chart: argo-cd
              targetRevision: 0.2.0
          velero:
            enabled: false
            destination:
              namespace: velero          
            source: |
              chart: velero
              repoURL: https://vmware-tanzu.github.io/helm-charts
              targetRevision: 1.5.3
          project-contour:
            enabled: true
            destination:
              namespace: project-contour
            source: |
              repoURL: https://charts.bitnami.com/bitnami
              chart: contour
              targetRevision: 4.1.0
              helm:
                releaseName: project-contour
                version: v3.5.1
                # https://github.com/bitnami/charts/blob/master/bitnami/contour/values.yaml
                values: |
                  configInline:
                    envoy-service-namespace: project-contour
                  prometheus:
                    serviceMonitor:
                      enabled: true
                  envoy:
                    service:
                      type: NodePort
                  contour:
                    manageCRDs: true
          argocd-image-updater:
            enabled: true
            destination: 
              namespace: argocd  
            source: |
              path: apps/argocd-image-updater/
              repoURL: https://github.com/nolte/argo-charts.git
              targetRevision: HEAD
          reloader:
            enabled: true
            destination: 
              namespace: operators  
            source: |
              path: deployments/kubernetes/chart/reloader
              repoURL: https://github.com/stakater/Reloader.git
              helm:
                version: v3.5.1

          konfigurator:
            enabled: true
            destination: 
              namespace: operators   
            source: |
              repoURL: https://github.com/stakater/Konfigurator.git
              path: deployments/kubernetes/chart/konfigurator
              targetRevision: v0.0.26
              helm:
                version: v3.5.1
                values: |
                  konfigurator:
                    deployCRD: true

          cert-manager:
            enabled: true
            destination: 
              namespace: cert-manager
            source: |
              repoURL: https://charts.jetstack.io
              chart: cert-manager
              targetRevision: v1.1.0
              helm:
                releaseName: cert-manager
                version: v3.5.1
                values: |
                  installCRDs: true
                  prometheus:
                    enabled: true
                    servicemonitor:
                      enabled: true

          monitoring:
            enabled: true
            destination: 
              namespace: monitoring   
            source: |
              repoURL: https://prometheus-community.github.io/helm-charts
              chart: kube-prometheus-stack
              targetRevision: 13.4.1
              helm:
                version: v3.5.1
                releaseName: monitoring
                values: |
                  prometheus:
                    ingress:
                      enabled: {{ .Values.global.ingress.enabled }}
                      annotations:
                        ingress.kubernetes.io/force-ssl-redirect: "true"
                        cert-manager.io/cluster-issuer: {{ .Values.global.ingress.clusterIssuer }}
                      hosts:
                       - prometheus.{{ .Values.global.ingress.domain }}
                      tls:
                        - secretName: prometheus-general-tls
                          hosts:
                          - prometheus.{{ .Values.global.ingress.domain }}                  
                  alertmanager:
                    ingress:
                      enabled: {{ .Values.global.ingress.enabled }}
                      annotations:
                        ingress.kubernetes.io/force-ssl-redirect: "true"
                        cert-manager.io/cluster-issuer: {{ .Values.global.ingress.clusterIssuer }}
                      hosts:
                       - alertmanager.{{ .Values.global.ingress.domain }}
                      tls:
                        - secretName: alertmanager-general-tls
                          hosts:
                          - alertmanager.{{ .Values.global.ingress.domain }}
                  # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
                  grafana:
                    enabled: {{ .Values.grafana.enabled }}
                    ingress:
                      enabled: {{ .Values.global.ingress.enabled }}
                      annotations:
                        ingress.kubernetes.io/force-ssl-redirect: "true"
                        cert-manager.io/cluster-issuer: {{ .Values.global.ingress.clusterIssuer }}
                      hosts:
                       - grafana.{{ .Values.global.ingress.domain }}
                      tls:
                        - secretName: grafana-tls
                          hosts:
                          - grafana.{{ .Values.global.ingress.domain }}
          forecastle:
            enabled: true
            destination: 
              namespace: operators   
            source: |
              path: deployments/kubernetes/chart/forecastle
              repoURL: https://github.com/stakater/Forecastle.git
              targetRevision: v1.0.62
              helm:
                version: v3.5.1
                values: |
                   forecastle:
                     ingress:
                       enabled: {{ .Values.global.ingress.enabled }}
                       annotations:
                         ingress.kubernetes.io/force-ssl-redirect: "true"
                         cert-manager.io/cluster-issuer: {{ .Values.global.ingress.clusterIssuer }}
                       tls:
                         - hosts:
                             - forecastle.{{ .Values.global.ingress.domain }}
                           secretName: forecastle-cert
                       hosts:
                         - host: forecastle.{{ .Values.global.ingress.domain }}
                           paths:
                           - /        
      version: v3.5.1
    path: charts/common-apps-argocd
    repoURL: https://github.com/nolte/argo-charts.git
    targetRevision: feature/collection-chart
  syncPolicy: {}