apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  annotations:
    reloader.stakater.com/auto: "true"  
spec:
  template:
    spec:
      containers:
        - name: external-dns
          # https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/pdns.md
          envFrom:
           - secretRef:
                name: pdns-access
          args:
          - --source=service,ingress # or ingress or both
          - --provider=pdns
          - --pdns-server=$(PDNS_SERVER_URL)
          - --pdns-api-key=$(PDNS_API_KEY)
          - --txt-owner-id=$(TXT_OWNER_ID)
          - --domain-filter=$(DOMAIN_FILTER)
          - --log-level=debug
          - --interval=30s          