destination:
  namespace: cert-manager
source:
  chart: cert-manager
  repoURL: https://charts.jetstack.io
  helm:
    values: |
      installCRDs: true
      prometheus:
        enabled: true
        servicemonitor:
          enabled: true