apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: initial
spec:
  entrypoint: initial-user
  arguments:
    parameters:
    - name: username
  templates: 
    - name: initial-user
      steps:
        - - name: select-pods
            arguments:
              parameters:
                - name: labelSelector
                  value: "app.kubernetes.io/component=server"
                - name: namespace
                  value: "argocd"
            templateRef:
              name: k8s-list
              template: get
        - - name: extract-name
            templateRef:
              name: jq-exec
              template: exec 
            arguments:
              parameters:
              - name: jsonExpression
                value: "{{steps.select-pods.outputs.parameters.pods}}|.items[0].metadata.name"              
        - - name: login
            arguments:
              parameters:
                - name: username
                  value: "{{workflow.parameters.username}}"
                - name: password
                  value: "{{steps.extract-name.outputs.parameters.result}}"
            templateRef:
              name: argocd-workflow-user
              template: login
