apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflow
namePrefix: argocd-

generatorOptions:
  disableNameSuffixHash: true


resources:
  - login.yaml
  - update-api-token.yaml
  - token.yaml
  - set-workflow-token.yaml
  - delete-token.yaml
  - initial-login.yaml

