# This example demonstrates the use of a git repo as a hard-wired input artifact.
# The argo repo is cloned to its target destination at '/src' for the main container to consume.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: login
spec:
  entrypoint: login
  arguments:
    parameters:
    - name: username
    - name: password
  templates:  
  - name: login
    inputs:
      parameters:
      - name: username
        value: "{{workflow.parameters.username}}"
      - name: password
        value: "{{workflow.parameters.password}}"        
    container:
      image: argoproj/argocd:v1.8.4 #TODO: switch to smaller one
      command: [sh, -c]
      args: ["argocd login $(ARGOCD_SERVER) --username {{inputs.parameters.username}} --password {{inputs.parameters.password}} --insecure --config /mnt/out/argo-auth.yaml"]
      envFrom:
      - configMapRef:
          name: argocd-auth-info
      volumeMounts:
        - name: out
          mountPath: /mnt/out
    volumes:
      - name: out
        emptyDir: { }
    outputs:
      parameters:
        - name: config
          valueFrom:
            path: /mnt/out/argo-auth.yaml