# This example demonstrates the use of a git repo as a hard-wired input artifact.
# The argo repo is cloned to its target destination at '/src' for the main container to consume.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: install
spec:
  entrypoint: install
  arguments:
    parameters:
    - name: appName
    - name: appPath
    - name: appCreateExtraArgs
    - name: destName
    - name: releaseName
    - name: appRevision
  templates:  
  - name: install
    templateRef:
       name: argocd-install
       template: install  
    inputs:
      parameters:
        - name: appName
          value: "{{workflow.parameters.appName}}"
        - name: appPath
          value: "{{workflow.parameters.appPath}}"
        - name: appCreateExtraArgs
          value: "--helm-version 3.5.1 --release-name {{workflow.parameters.releaseName}} {{workflow.parameters.appCreateExtraArgs}}"
        - name: destName
          value: "{{workflow.parameters.destName}}"
        - name: releaseName
          value: "{{workflow.parameters.releaseName}}"
        - name: appRepo
          value: "https://github.com/nolte/argo-charts.git"          
        - name: appNamespace
          value: "argocd"
        - name: appRevision
          value: "{{workflow.parameters.appRevision}}"