# This example demonstrates the use of a git repo as a hard-wired input artifact.
# The argo repo is cloned to its target destination at '/src' for the main container to consume.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create
spec:
  entrypoint: install
  arguments:
    parameters:
    - name: appName
    - name: appPath
    - name: appCreateExtraArgs
      value: "--helm-version 3.5.1 --release-name {{inputs.parameters.releaseName}} {{inputs.parameters.appCreateExtraArgs}}"
    - name: destName
    - name: releaseName
    - name: appRevision
      value: master
    #- name: appRepo
    #  value: "https://github.com/nolte/argo-charts.git"              
    #- name: appNamespace
    #  value: argocd  
  templates:  
  - name: install
    inputs:
      parameters:
      - name: appName
      - name: appPath
      - name: appCreateExtraArgs
        #value: "--helm-version 3.5.1 --release-name {{inputs.parameters.releaseName}} {{workflow.parameters.appCreateExtraArgs}}"
      - name: destName
      - name: releaseName
      - name: appRevision
        #value: master
      - name: appRepo
        #value: "{{arguments.parameters.appRepo}}"
        value: "https://github.com/nolte/argo-charts.git"              
      - name: appNamespace
        #value: "{{arguments.parameters.appNamespace}}"
        value: argocd  
    #arguments:
    #  parameters:
    #    - name: appName
    #    - name: appPath
    #    - name: appCreateExtraArgs
    #    - name: destName
    #    - name: releaseName
    #    - name: appRepo
    #    - name: appNamespace
    #    - name: appRevision
    templateRef:
       name: argocd-install
       template: install            