destination:
  namespace: minio

source:
  # https://github.com/minio/charts/blob/master/minio/values.yaml
  chart: minio
  repoURL: https://helm.min.io/
  targetRevision: 8.0.9
  helm:
    version: v3
    values: |
      metrics:
        serviceMonitor:
          enabled: true
      buckets:
        - name: tf-states
          policy: none
          purge: false
        - name: public-shared
          policy: public
          purge: false