# This example demonstrates the use of a git repo as a hard-wired input artifact.
# The argo repo is cloned to its target destination at '/src' for the main container to consume.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: minio
spec:
  entrypoint: install
  arguments:
    parameters:
    - name: destName
    - name: appRevision
  templates:
  - name: install
    templateRef:
       name: app-install
       template: install  
    inputs:
      parameters:
        - name: appName
          value: "seed-minio"
        - name: appPath
          value: "charts/argocd-minio/"
        - name: "releaseName"
          value: "minio"
        - name: "destName"
          value: "{{workflow.parameters.destName}}"
        - name: "appRevision"
          value: "{{workflow.parameters.appRevision}}"
        - name: "appCreateExtraArgs"
          value: ""
