# This example demonstrates the use of a git repo as a hard-wired input artifact.
# The argo repo is cloned to its target destination at '/src' for the main container to consume.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: vault
spec:
  entrypoint: install
  arguments:
    parameters:
    - name: destName
    - name: appRevision
  templates:  
    - name: install
      inputs:
        parameters:
        - name: appName
          value: "seed-vault"
        - name: appPath
          value: "charts/argocd-vault/"
        - name: "releaseName"
          value: "vault"
        - name: "destName"
          value: "{{arguments.parameters.destName}}"
        - name: "appRevision"
          value: "{{arguments.parameters.appRevision}}"
        #- name: "appCreateExtraArgs"
        #  value: ""
      steps:
      - - name: vault
          arguments:
            parameters:
              - name: appName
                value: "{{inputs.parameters.appName}}"
              - name: appPath
                value: "{{inputs.parameters.appPath}}"
              - name: "releaseName"
                value: "{{inputs.parameters.releaseName}}"
              - name: "destName"
                value: "{{inputs.parameters.destName}}"              
              - name: "appRevision"
                value: "{{inputs.parameters.appRevision}}"
              #- name: appRepo
              #  value: "{{inputs.parameters.appRepo}}"
              #- name: appNamespace 
              #  value: "{{inputs.parameters.appNamespace}}"
              - name: "appCreateExtraArgs"
                value:  ""
          templateRef:
             name: app-create
             template: install  