# This example demonstrates the use of a git repo as a hard-wired input artifact.
# The argo repo is cloned to its target destination at '/src' for the main container to consume.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: vault
spec:
  entrypoint: install
  inputs:
    parameters:
    - name: destName
    - name: appRevision
  templates:  
    - name: install
      inputs:
        parameters:
        - name: destName
        - name: appRevision
      steps:
      - - name: vault
          arguments:
            parameters:
              - name: appName
                value: "seed-vault"
              - name: appPath
                value: "charts/argocd-vault/"
              - name: "releaseName"
                value: "vault"
              - name: "destName"
                value: "{{inputs.parameters.destName}}"
              - name: "appRevision"
                value: "{{inputs.parameters.appRevision}}"
              - name: "appCreateExtraArgs"
                value: ""
          templateRef:
             name: app-create
             template: install  