# This example demonstrates the use of a git repo as a hard-wired input artifact.
# The argo repo is cloned to its target destination at '/src' for the main container to consume.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: get
spec:
  entrypoint: get
  inputs:
    parameters:
    - name: appName
  templates:  
  - name: get
    inputs:
      parameters:
      - name: appName
        value: "{{workflow.parameters.appName}}"
    container:
      image: argoproj/argocd:v1.8.4 #TODO: switch to smaller one
      command: [sh, -c]
      args: ["env && argocd app get {{inputs.parameters.appName}} --auth-token $ARGOCD_AUTH_TOKEN --server $ARGOCD_SERVER:80 --insecure --loglevel debug -ojson > /mnt/out/app.json"]
      envFrom:
      - configMapRef:
          name: argocd-auth-info
      - secretRef:
          name: argocd-auth
      volumeMounts:
        - name: out
          mountPath: /mnt/out
    volumes:
      - name: out
        emptyDir: { }
    outputs:
      parameters:
        - name: app
          valueFrom:
            path: /mnt/out/app.json