apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflow
namePrefix: argocd-

generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:
- name: auth-info
  literals:
    - ARGOCD_SERVER=argocd-server.argocd.svc
    - ARGOCD_GRPC_WEB="true"
    - ARGOCD_INSECURE="true"
    - ARGOCD_PLAINTEXT="true"

resources:
  - app-get.yaml
  - app-create.yaml
  - app-install.yaml
  - app-sync.yaml
  - app-set.yaml