apiVersion: v2
name: forecastle
version: 1.0.0
sources:
  - https://github.com/stakater/Forecastle
dependencies:
  - name: common-app
    repository: https://nolte.github.io/argo-charts/
    version: 1.1.1