apiVersion: v2
name: forecastle
version: 1.6.0
appVersion: v0.0.79
sources:
  - https://github.com/stakater/Forecastle
dependencies:
  - name: common-app
    repository: https://nolte.github.io/argo-charts/
    version: 1.2.0