# Set annotations on the deployment/statefulset/daemonset
controllerAnnotations: {}
# Set labels on the deployment/statefulset/daemonset
controllerLabels: {}

nameOverride: ""
fullnameOverride: ""

project: default

destination:
  name: in-cluster
  namespace: argocd

syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true
  ignoreDifferences: {}