apiVersion: v2
name: argocd-keycloaks
version: 1.6.0
appVersion: 9.9.0
sources:
  - https://github.com/codecentric/helm-charts
  - https://github.com/jboss-dockerfiles/keycloak
  - https://github.com/bitnami/charts/tree/master/bitnami/postgresql
dependencies:
  - name: common-app
    repository: https://nolte.github.io/argo-charts/
    version: 1.2.0