{{ $dot := . }}
{{- range $key, $val := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{$key}}
  labels:
    {{- include "common.labels" $dot | nindent 4 }}
spec:
  destination:
{{- tpl (default $val.destination $dot.Values.global.destination) $dot | nindent 4 }}
  project: {{ tpl (default $val.project $dot.Values.global.project) $dot}}
  source:
{{- tpl $val.source $dot | nindent 3 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}