{{ $dot := . }}
{{- range $key, $val := .Values.apps }}
{{ if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{$key}}
  labels:
    {{- include "common.labels" $dot | nindent 4 }}
spec:
  destination:
    name: {{ tpl (default $val.destination.name $dot.Values.global.destination.name) $dot}}
    namespace: {{ tpl $val.destination.namespace $dot }}
  project: {{ tpl (default $val.project $dot.Values.global.project) $dot}}
  source:
{{- tpl $val.source $dot | nindent 3 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
{{- end }}