apiVersion: v2
name: argocd-gitea
version: 1.0.0
appVersion: 2.1.11
sources:
 - https://gitea.com/gitea/helm-chart/
dependencies:
  - name: common-app
    repository: https://nolte.github.io/argo-charts/
    version: 1.2.0