# https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
global:
  domain: 172-17-0-1.sslip.io
  clusterIssuer: cluster-issuer
  project: seed

  destination:
    namespace: argocd
    name: in-cluster

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

releaseName: tp-baseline

projectContour:
  enabled: true

certManager:
  enabled: true

reloader:
  enabled: true

monitoring:
  enabled: true

forecastle:
  enabled: true
  ingress:
    enabled: true

konfigurator:
  enabled: true


source:
  repoURL: 'https://github.com/nolte/argo-charts.git'
  path: seeds/collection-argocd-baseline/
  targetRevision: master


project: cicd
