apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt
spec:
  secretName: {{.Values.injector.certs.secretName}}
  dnsNames:
  - {{ template "vault.fullname" . }}.{{.Release.Namespace}}.svc
  - {{ template "vault.fullname" . }}-internal.{{.Release.Namespace}}.svc
{{- range .Values.injector.certs.dnsNames }}
  - {{ . }}
{{- end }}
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    group: cert-manager.io