apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "vault.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{.Values.vault.injector.certs.secretName}}
  dnsNames:
  - {{ template "vault.fullname" . }}.{{.Release.Namespace}}.svc
  - {{ template "vault.fullname" . }}-internal.{{.Release.Namespace}}.svc
{{- range .Values.vault.injector.certs.dnsNames }}
  - {{ . }}
{{- end }}
  issuerRef:
    name: {{ .Values.vault.injector.certs.issuerRef.name | quote }}
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: {{ .Values.vault.injector.certs.issuerRef.kind | quote }}
    group: cert-manager.io