# https://www.vaultproject.io/docs/commands/operator/unseal
# https://www.vaultproject.io/docs/platform/k8s/helm/run
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ template "vault.fullname" . }}-flow-unseal
  namespace: {{ default .Release.Namespace .Values.workflow.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}-vault-unseal
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: workflow
spec:
  entrypoint: unseal-flow
  arguments:
    parameters:
      - name: labelSelector
        value: "component=server"
      - name: namespace
        value: "vault"
  templates:
    - name: unseal-flow
      steps:
        - - name: select-pods
            arguments:
              parameters:
                - name: labelSelector
                  value: "component=server"
                - name: namespace
                  value: "vault"
            templateRef:
              name: k8s-list
              template: get
        - - name: extract-names
            templateRef:
              name: jq-exec
              template: exec 
            arguments:
              parameters:
              - name: jsonExpression
                value: "{{ printf "{{steps.select-pods.outputs.parameters.pods}}|.items[].metadata.name|[.]" }}"
            
        - - name: unseal
            template: unseal-pod
            arguments:
              parameters:
              - name: podName
                value: "{{ printf "{{item}}" }}"
              - name: namespace
                value: "vault"
            withParam: "{{ printf "{{steps.extract-names.outputs.parameters.result}}" }}"


    - name: unseal-pod
      inputs:
        parameters:
          - name: podName
          - name: namespace
      steps:  
       - - name: unseal-pod-keys
           templateRef:
             name: k8s-exec
             template: exec
           continueOn:
              failed: true
           arguments:
             parameters:
             - name: podName
               value: "{{ printf "{{inputs.parameters.podName}}" }}"
             - name: namespace
               value: "{{ printf "{{inputs.parameters.namespace}}" }}"
             - name: execCommand
               value: "vault status -format=json"

       - - name: vault-status-parse
           templateRef:
             name: jq-exec
             template: exec
           arguments:
             parameters:
             - name: jsonExpression
               value: "{{ printf "{{steps.unseal-pod-keys.outputs.parameters.result}}|.sealed" }}"


       - - name: operator-init
           when: "{{ printf "{{steps.unseal-pod-keys.exitCode}} == 2" }}"
           template: unseal-token
           arguments:
             parameters:
             - name: podName
               value: "{{ printf "{{inputs.parameters.podName}}" }}"
             - name: namespace
               value: "{{ printf "{{inputs.parameters.namespace}}" }}"

    - name: unseal-token
      inputs:
        parameters:
          - name: podName
          - name: namespace
      steps:
       - - name: operator-init
           templateRef:
             name: k8s-exec
             template: exec        
           arguments:
             parameters:
             - name: podName
               value: "{{ printf "{{inputs.parameters.podName}}" }}"
             - name: namespace
               value: "{{ printf "{{inputs.parameters.namespace}}" }}"
             - name: execCommand
               value: "vault operator init -format=json"
      
       - - name: vault-extract-unseal-keys
           templateRef:
             name: jq-exec
             template: exec
           arguments:
             parameters:
             - name: jsonExpression
               value: "{{ printf "{{steps.operator-init.outputs.parameters.result}}|.unseal_keys_b64[0:3]" }}"

       - - name: unseal-token
           templateRef:
             name: k8s-exec
             template: exec
           withParam: "{{ printf "{{steps.vault-extract-unseal-keys.outputs.parameters.result}}" }}"  
           arguments:
             parameters:
             - name: podName
               value: "{{ printf "{{inputs.parameters.podName}}" }}"
             - name: namespace
               value: "{{ printf "{{inputs.parameters.namespace}}" }}"
             - name: execCommand
               value: "vault operator unseal {{ printf "{{item}}" }}"