# https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/values.yaml
destination:
  namespace: mosquitto

source:
  chart: mosquitto
  repoURL: https://halkeye.github.io/helm-charts/
